<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TalksOps.ApiClient\TalksOps.ApiClient.csproj" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.4.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>0eb39914-0cb7-41e6-88a9-94ef6ef3829d</UserSecretsId>
  </PropertyGroup>

</Project>
